### ISSUE TITLE
Can't post with just auth

### ISSUE THREAD

**Issue by mevering** [LamerLink/quick_rest#2]
If you try to just post to an endpoint with the `requests` `auth` keyword it will give an `ArgumentError`.

Passing `json_data=True` seems to be a workaround for now.

**Comment by michaeleveringham** [comment]
You can now omit `json_data` or `text_data` and not get an `ArgumentError`, but not you may get a `ServerError: 415: Unsupported Media Type` unless you specify either the `Content-Type` or the payload. 

For instance, you could now instead just pass `json={}` in your use-case above.

```python
client= Client('https://some.site/')
response = client.post('route', json={})
```
